### ISSUE TITLE
Initialization Causes "ReferenceError: window is not defined"

### ISSUE THREAD

**Issue by KryptoNova** [ericblade/quagga2#108]
@ericblade , Thank you for your hard work and keeping Quagga alive!

I am not exactly sure what I am doing wrong, but any version after 0.10.0 causes a "ReferenceError: window is not defined" error when the Quagga object is instantiated.

I am using node version 12.3.1 and the code that causes the error is:

`var Quagga = require('@ericblade/quagga2').default`

I am not familiar with the code base enough to make recommendations.  However, based on the error it seems that perhaps the catch that determines if this is a browser or node implementation of Quagga2 is broke.  It seems to be defaulting to browser.

Is there a property that I should be setting when initializing the Quagga object to eliminate the dependence on a browser and work like version 0.10.0 does?

**Comment by ericblade** [comment]
Hi there.  I restarted versioning at 0.0.1 when i forked, and current is 0.0.14 . . the original line ended at 0.12.x .. so could you clarify that this was happening with the original fork or no, or just mine after 0.0.10 (which is where i started using typescript in the main branch...)

Does it trigger solely with the given line of code, or is there more code involved?   
This seems more than a bit weird, considering that the tests run in node, and i am presently maintaining two dependent modules that i test routinely against it, both in node..

**Comment by KryptoNova** [comment]
It is happening with any version after 0.10.0 and that is the only line of code that is involved with generating the error.

I set the version of @ericblade/Quagga2 to be 0.14.0 and then backed it down to version 0.10.0. That was the only way to eliminate the error.

I was thinking that perhaps there was something in the `.default` in that statement that assumed a browser based implementation.

**Comment by KryptoNova** [comment]
I did a little more digging.

It looks like this error is related to line 10 in quagga.js.

`})(window, function(__WEBPACK_EXTERNAL_MODULE__27__) {`

It seems that when window is referenced in the above line it is not initialized.

Also, deleted the node_modules directory and ran npm install again to build it fresh from the 0.14.0 version.  I noticed this message in the npm output.

`npm WARN webpack-cli@3.3.10 requires a peer of webpack@4.x.x but none is installed. You must install peer dependencies yourself.`

I am not familiar with webpack-cli, but I believe the line that is causing the error seems to be related to WEBPACK.

Let me know if you have any other questions or have any suggestions on what may need to be done.

**Comment by ericblade** [comment]
@KryptoNova thanks for finding this issue, and I'm still absolutely boggled as to why testing didn't find it -- either it's not testing in node like i think it is, or one of the many components is stubbing a window object in, and i'm not sure which is more likely the thing to try to track it down :-D

I did find that building the node version of the lib as commonjs from webpack does give a correct result .... and now that i'm reading the result, it's not correct. Oh, pooh.

onto 0.0.16 i guess. argh. :-D

**Comment by ericblade** [comment]
This is from 0.0.16

![image](https://user-images.githubusercontent.com/1451847/72499694-8cb44000-3800-11ea-96dd-dee55b716887.png)
