### ISSUE TITLE
Added br causes flickering

### ISSUE THREAD

**Issue by kevinpapst** [ericblade/quagga2#140]
There is a piece of code
```
function quagga_initCanvas() {
    // ... snip ...
      var clearFix = document.createElement('br');
      clearFix.setAttribute('clear', 'all');

      if ($viewport) {
        $viewport.appendChild(clearFix);
      }
    }
```

which makes the final HTML page jump after rendering the video element. Is there any technical reason for having this? Fromy my perspective it would be better to document any floating issue, instead of injecting this "rather broken fix" into the document.

Do you see any possibility of either reomving this completely or making it configurable?

**Comment by ericblade** [comment]
Hmm. I'd not noticed that in the code before, thanks for pointing it out.  I can't speak to the specific reason as to why it was added there (perhaps the commit history might give some idea), but it does certainly look a bit out of place, as i can't recall seeing a br clear trick used in many years now

It looks like if you don't have a canvas element with class "drawingBuffer", that is when it does this.  Now, I'm just reading this for the first time, so i'm going to see if I can tell what it's doing and maybe suss out a why or something :-)

If there's no canvas.drawingBuffer, then create a canvas.drawingBuffer .. if there is a viewport, attach the new drawingBuffer to it, then create a br clear element, and if there's a viewport, attach the br clear to it.

yeaaah, my guess is that it's there to turn off any floating that someone might've turned on.  br clear is so old, it's hardly mentioned in the last 5 years.  

I wouldn't expect there to be any problem removing it .. and I'd probably also consider wrapping a large portion of that function into a single if($viewport) wrapper, as much of it has no effect at all if there's no viewport set, but still does stuff that it doesn't need to do.

I'd totally be behind a pull request to clean that up, or I'll try to get to it myself when I have some time to work on this.

**Comment by kevinpapst** [comment]
Now that you mention it... is it recommended to add a `canvas.drawingBuffer` manually? There is nothing in the README about it. I was a bit confused when I used quagga the first time, as I had suddenly this empty element that took up a lot of screen space but didn't actually display anything. Thats why I added a css rule to hide it.

I can provide a PR, but it would not be more than "a lucky guess".

**Comment by ericblade** [comment]
Unfortunately, I can't read the mind of the previous maintainers, so I don't have a specific answer as to "is it recommended".  If you do add one, that'll prevent the br clear tag being added.  

I suspect that simply removing that piece should be fine -- it might be possible that some people's implementations may end up needing a tweak after, but i'd rather make that change, than have it inserting a bunch of unexpected html.  The thing I don't even know is, is it even necessary that a drawingBuffer be created at all, if the user has no intent of using it?  

I think we're all too new to be able to answer a lot of questions without digging through the code to answer them.. 

assuming you're using a packing system like webpack or something to include quagga, you should be able to build a dev version by doing:

````
npm run build && npm run test && npm link
````
then in the place where you want to build using the dev version, do
````
npm link @ericblade/quagga2
````
then your web app will be using the dev version you've built.  
When you make changes to your local copy of quagga2, then you should be able to see the changes update in your web app by just doing ````npm run build && npm run test````  (i always run tests after building) then re-building your web app (or if you're using a hot reload service, it should pick up automatically)

**Comment by kevinpapst** [comment]
> Unfortunately, I can't read the mind of the previous maintainers, so I don't have a specific answer as to "is it recommended". 
LOL, I am new to the project. You are the maintainer (even though I saw that you forked it from the original repo), so you will get such questions, no way around it 😁 Not all users might be coming from the discussion in the original repo.

> If you do add one, that'll prevent the br clear tag being added.

I will try, good hint. A lot of these infos should go into the README. I will contribute when I find solutions to my problems. Do you want it in the README (Tips & Tricks section for example) or would you prefer to keep the README to the minimum and move new docs to the wiki?

> is it even necessary that a drawingBuffer be created at all, if the user has no intent of using it?

Seems you know at least what it is good for, "drawingBuffer" is not mentioned in the docs at all and so I believed that it is required for "something". But I can try with some JS to remove it after page load and report back.

**Comment by ericblade** [comment]
In quagga.js initCanvas(), the drawingBuffer canvas is assigned to _canvasContainer.dom.overlay and it's draw context is assigned to _canvasContainer.ctx.overlay . 

Source code search for usage of ".overlay" seems to indicate that it's not really used by Quagga itself, but is exposed as Quagga.canvas.dom.overlay and Quagga.canvas.ctx.overlay .  So, there's probably at least some code that expects it to be there, i see some things referencing it .. anyway, it's used in a user's onProcessed function to draw information about what's going on.

**Comment by kevinpapst** [comment]
Okay, I re-read the code and my impression is that the `drawingBuffer` is only used to display the data which was found while scanning, by replicating the video element and painting the rectangular (and other infos) about the detected barcode => in development. 

So I would propose to either put the creation of it into a `if (ENV.development) {` block or maybe use the `config.debug` value to decide whether it should be created. 
Like done here already: https://github.com/ericblade/quagga2/blob/master/src/decoder/barcode_decoder.js#L57

Right now I added a CSS rule `canvas.drawingBuffer { display: none; }` which feels stupid.
Actually removing it from the Dom doesn't cause any issues. I tried with a patched build and also by calling `document.getElementsByClassName('drawingBuffer')[0].remove();`. after `Quagga.start();`. Everything still worked normally.

**Comment by ericblade** [comment]
yea.. i noticed that there are a few places where it manipulates that canvas (ie on resize of the container) that might need a check to validate that it exists or not before manipulating it, but i think that it would be good to support not having an explicitly created canvas, if the user doesn't need to draw anything.
