### ISSUE TITLE
Problem when scanning several barcodes

### ISSUE THREAD

**Issue by mrezzonico** [ericblade/quagga2#153]
Hi all,

I have several barcodes that are vertically aligned.
In this situation it is difficult to scan the correct one.
Is it possible to force to scan only the barcode near an horizontal center line ?

Thanks
Miche

**Comment by ericblade** [comment]
Yes, if you turn off the "locate" parameter, then it will turn off the auto-location of barcodes, and you can specify an area of the screen to search, using "area", i believe it's called.  Search through the README for those terms, and that should help you there.  I think one of the old demonstrations might have an example, too, but not real sure on that.  

What I have not been so successful at, is trying to indicate using the Canvas exactly where that area on screen is.  Should you happen to come up with a way to get it to align right that works on mobile, I'd love to know :)

**Comment by mrezzonico** [comment]
Hi Eric,

thanks a lot, this solved my problem.

In the file live_w_locator.js I set:
 "locate: false"

and in the file quagga.js I set:
top: "48%",
right: "0%",
left: "%0",
bottom: "48%"

Thanks again for your help.
Miche
