### ISSUE TITLE
Provide the dist/quagga.js

### ISSUE THREAD

**Issue by jbramsden** [ericblade/quagga2#156]
Hi,

First, well done for taking on Quagga and improving it!

I would like to test out the examples without having to use NPM. Would you please be able to provide the /dist directory and files as part of the git repo? Or provide them as part of the release?

Thanks in advance

Jason

**Comment by ericblade** [comment]
Hi!  You're welcome! :)

Putting the built files into the repo is widely regarded as a bad idea -- it leads to problems dealing with merge conflicts, as well as forgetting to update either the built code or the source code when changes are made.

We've been discussing this on #42 , if there's some automated way of doing it when a release is created, then great, i'd be happy to do it, especially if it helps automate github releases vs npm releases, which right now are completely separate.

You can always checkout whatever version of the git repo you'd like, then 'npm run build' in it to get the dist files.  I know that's not without npm, so not exactly what you're looking for.  

The last thing I need is adding more manual steps to keep track of, and the first thing I need is more automation to help keep things together. :-D  And the second thing I need is more time in the day to figure it all out :-)

Closing this in favor of #42, as we've already been discussing this there, so please comment there :)
