### ISSUE TITLE
Code 32

### ISSUE THREAD

**Issue by stefanocali** [ericblade/quagga2#157]
It’a possibile to implement Code 32 ( Italian PharmaCode ) ?

**Comment by ericblade** [comment]
Hi! Great question! (i was just about to reply to your post in the other repo :) ) 

I definitely have an interest in expanding the barcode types that are available -- part of the reason I've added the ability to add additional decoders.

It does look like it is something that probably can be added, considering that according to this document: https://barcodeguide.seagullscientific.com/Content/Symbologies/Code_32.htm ... it is an offshoot of Code 39, which is already supported.  

This document provides more information about it: https://help.accusoft.com/BarcodeXpress/v9.0/activex/Code%2032.html

This may actually be *quite* simple to add support for, either as a separate decoder that extends Code 39, or as a supplement to Code 39.  

If there's anyone in the group that is paying attention, and would like to take on the task of working out how to put together a new decoder, this looks like a very low hanging fruit.

**Comment by ericblade** [comment]
@kevinpapst @WardLootens 
If either of you are interested in taking a look at putting together a new decoder, or extending an existing one, this task might interest you, and also might help direct some of the other efforts going on

**Comment by stefanocali** [comment]
The length of any PHARMACODE must be 10 characters.

This code is adopted by the Italian Ministry of Health for the codification of pharmaceutical products.
The clear code is made up of eight digits that identify the type of packaging for each medicinal product, preceded by the character A and followed by a check digit (Check Digit)
The overall nine digits are then represented in base 32 with six alphanumeric characters, using (with a CODE39 barcode) the 10 decimal digits and the 26 characters of the alphabet, with the exclusion of the vowels A, E, I, O.

How the Check Digit is calculated

The first 8 digits of the code must be taken

those in even positions (2,4,6, ...) must be multiplied by 2

from the result use each single digit individually

add all the numbers (those in odd position normally, those in even position using single digits)

Divide the sum by 10

The rest obtained is the control character.

Example:

02009602

0x1 = 0
2 × 2 = 4
0x1 = 0
0x2 = 0
9 × 1 = 9
6 × 2 = 12 (1 + 2)
0x1 = 0
2 × 2 = 4
___________
sum 20 (4 + 9 + 1 + 2 + 4)

20/10 = 0

the exact code is

020096020

TRANSPOSITION FROM CLEAR CODE TO BAR CODE and vice versa

If the plaintext code is A020096020 the barcode is 0M590N

Conversion table 

Figure | 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10 | 11 | 12 | 13 | 14 | 15
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
Character | 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | B | C | D | F | G | H
  |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |  
Figure | 16 | 17 | 18 | 19 | 20 | 21 | 22 | 23 | 24 | 25 | 26 | 27 | 28 | 29 | 30 | 31
Character | J | K | L | M | N | P | Q | R | S | T | U | V | W | X | Y | Z

From clear code to bar code

020096020/32 5 (33554432) = 0 ( 0 ) with the rest of 20096020
20096020/32 4 (1048576) = 19 ( M ) with the rest of 173076
173076/32 3 (32768) = 5 ( 5 ) with the rest of 9236
9236/32 2 (1024) = 9 ( 9 ) with the rest of 20
20/32 1 (32) = 0 ( 0 ) with the remainder of 20
20/32 0 (1) = 20 ( N )
the resulting sequence is 0M590N

From barcode to plaintext

0 = 0 x 32 5 (33554432) = 0
M = 19 x 32 4 (1048576) = 19922944
5 = 5 x 32 3 (32768) = 163840
9 = 9 x 32 2 (1024) = 9216
0 = 0 x 32 1 (32) = 0
N = 20 x 32 0 (1) = 20
total = 20096020 (so with 9 digits it becomes 020096020)

**Comment by stefanocali** [comment]
I started by creating this file and changing the properties variable with those of Code 32  ( Italian PharmaCode )

```
import BarcodeReader from './barcode_reader';
import ArrayHelper from '../common/array_helper.ts';

function Code32Reader() {
    BarcodeReader.call(this);
}

var properties = {
    ALPHABETH_STRING: {value: '0123456789BCDFGHJKLMNPQRSTUVWXYZ*'},
    ALPHABET: {value: [48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 66, 67, 68, 70, 71, 72, 74, 75, 76, 77, 78,
        80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 42]},
    CHARACTER_ENCODINGS: {value: [0x034, 0x121, 0x061, 0x160, 0x031, 0x130, 0x070, 0x025, 0x124, 0x064, 0x049,
        0x148, 0x019, 0x058, 0x00D, 0x10C, 0x01C, 0x103, 0x043, 0x142, 0x013, 0x052, 0x007, 0x106, 0x046, 0x016, 
        0x181, 0x0C1, 0x1C0, 0x091, 0x190, 0x0D0, 0x094,
    ]},
    ASTERISK: {value: 0x094},
    FORMAT: {value: 'code_32', writeable: false},
};

Code32Reader.prototype = Object.create(BarcodeReader.prototype, properties);
Code32Reader.prototype.constructor = Code32Reader;

Code32Reader.prototype._decode = function() {
    var self = this,
        counters = [0, 0, 0, 0, 0, 0, 0, 0, 0],
        result = [],
        start = self._findStart(),
        decodedChar,
        lastStart,
        pattern,
        nextStart;

    if (!start) {
        return null;
    }
    nextStart = self._nextSet(self._row, start.end);

    do {
        counters = self._toCounters(nextStart, counters);
        pattern = self._toPattern(counters);
        if (pattern < 0) {
            return null;
        }
        decodedChar = self._patternToChar(pattern);
        if (decodedChar < 0){
            return null;
        }
        result.push(decodedChar);
        lastStart = nextStart;
        nextStart += ArrayHelper.sum(counters);
        nextStart = self._nextSet(self._row, nextStart);
    } while (decodedChar !== '*');
    result.pop();

    if (!result.length) {
        return null;
    }

    if (!self._verifyTrailingWhitespace(lastStart, nextStart, counters)) {
        return null;
    }

    return {
        code: result.join(''),
        start: start.start,
        end: nextStart,
        startInfo: start,
        decodedCodes: result,
    };
};

Code32Reader.prototype._verifyTrailingWhitespace = function(lastStart, nextStart, counters) {
    var trailingWhitespaceEnd,
        patternSize = ArrayHelper.sum(counters);

    trailingWhitespaceEnd = nextStart - lastStart - patternSize;
    if ((trailingWhitespaceEnd * 3) >= patternSize) {
        return true;
    }
    return false;
};

Code32Reader.prototype._patternToChar = function(pattern) {
    var i,
        self = this;

    for (i = 0; i < self.CHARACTER_ENCODINGS.length; i++) {
        if (self.CHARACTER_ENCODINGS[i] === pattern) {
            return String.fromCharCode(self.ALPHABET[i]);
        }
    }
    return -1;
};

Code32Reader.prototype._findNextWidth = function(counters, current) {
    var i,
        minWidth = Number.MAX_VALUE;

    for (i = 0; i < counters.length; i++) {
        if (counters[i] < minWidth && counters[i] > current) {
            minWidth = counters[i];
        }
    }

    return minWidth;
};

Code32Reader.prototype._toPattern = function(counters) {
    var numCounters = counters.length,
        maxNarrowWidth = 0,
        numWideBars = numCounters,
        wideBarWidth = 0,
        self = this,
        pattern,
        i;

    while (numWideBars > 3) {
        maxNarrowWidth = self._findNextWidth(counters, maxNarrowWidth);
        numWideBars = 0;
        pattern = 0;
        for (i = 0; i < numCounters; i++) {
            if (counters[i] > maxNarrowWidth) {
                pattern |= 1 << (numCounters - 1 - i);
                numWideBars++;
                wideBarWidth += counters[i];
            }
        }

        if (numWideBars === 3) {
            for (i = 0; i < numCounters && numWideBars > 0; i++) {
                if (counters[i] > maxNarrowWidth) {
                    numWideBars--;
                    if ((counters[i] * 2) >= wideBarWidth) {
                        return -1;
                    }
                }
            }
            return pattern;
        }
    }
    return -1;
};

Code32Reader.prototype._findStart = function() {
    var self = this,
        offset = self._nextSet(self._row),
        patternStart = offset,
        counter = [0, 0, 0, 0, 0, 0, 0, 0, 0],
        counterPos = 0,
        isWhite = false,
        i,
        j,
        whiteSpaceMustStart;

    for ( i = offset; i < self._row.length; i++) {
        if (self._row[i] ^ isWhite) {
            counter[counterPos]++;
        } else {
            if (counterPos === counter.length - 1) {
                // find start pattern
                if (self._toPattern(counter) === self.ASTERISK) {
                    whiteSpaceMustStart = Math.floor(Math.max(0, patternStart - ((i - patternStart) / 4)));
                    if (self._matchRange(whiteSpaceMustStart, patternStart, 0)) {
                        return {
                            start: patternStart,
                            end: i,
                        };
                    }
                }

                patternStart += counter[0] + counter[1];
                for ( j = 0; j < 7; j++) {
                    counter[j] = counter[j + 2];
                }
                counter[7] = 0;
                counter[8] = 0;
                counterPos--;
            } else {
                counterPos++;
            }
            counter[counterPos] = 1;
            isWhite = !isWhite;
        }
    }
    return null;
};

export default Code32Reader;

```

**Comment by WardLootens** [comment]
> @kevinpapst @WardLootens
> If either of you are interested in taking a look at putting together a new decoder, or extending an existing one, this task might interest you, and also might help direct some of the other efforts going on

I'd be interested, but honestely, due to Covid-19 measures over here, I now have 2 fulltime jobs: my normal job, and taking care of my 2 young sons now daycare is closed ;-)
So for the coming week, I won't have the time let alone the energy to engage in this.  Unfortunately...

**Comment by ericblade** [comment]
@stefanocali it'd be a lot easier if i could see a diff there.. if you fork and make a pull req, then it would be easier for me to see how that works side by side.

There's a little bit more to do involving some of the other files to add another reader to the code, and i'm not entirely sure where all that is exactly -- i don't think anyone's added a new reader for quite a long time, but if you search on the class name of the one you're copying from, you can probably figure that out pretty quickly.

That said, it would be better to extend the Code 39 reader, and only change any properties/functions that are necessary to get it to work with Code 32.  Interestingly, I notice that the spec as you've quoted says it is always 10 characters, and there are several other barcodes that also have specific character lengths -- which is not something that i can recall seeing addressed in any of the decoders that i've converted to TypeScript so far.

**Comment by stefanocali** [comment]
Hi Eric, I made the change to the files, but I don't know why I canceled the assignment to this issue. Let me know if it's all fine! Thanks, see you soon
