### ISSUE TITLE
Is there any GS1-128/EAN-128 support?

### ISSUE THREAD

**Issue by chenyong** [ericblade/quagga2#170]
We are running quagga2 and run into codes in GS1-128. At first we thought it was CODE-128 since they share the same start code and GS1-128 is mostly based on CODE-128 but with differences in "FNC 1"s.

https://en.wikipedia.org/wiki/GS1-128

I noticed GS1-128 also uses the name EAN-128. Quagga2 has EAN support, does it contain work related to EAN-128?

Related option in jsbarcode https://github.com/lindell/JsBarcode/wiki/CODE128#ean128-option-for-code128

**Comment by chenyong** [comment]
Tried with some examples, looks like it's supported, just not easy to recognize, especially for the ones with more chars.

![image](https://user-images.githubusercontent.com/25790987/79314296-22608800-7f34-11ea-9e2b-4444fda37819.png)

![image](https://user-images.githubusercontent.com/25790987/79314323-27253c00-7f34-11ea-9062-861775d38bed.png)

**Comment by ericblade** [comment]
Hi @chenyong .. great question.  At least for these two images, they seem to work fine with the code128 reader, as long as there is sufficient whitespace around the barcode.

I've added 25 pixels of whitespace in each dimension on both of them, and was able to read them using

```
Quagga.decodeSingle({
    decoder: {
        readers: [ 'code_128_reader' ],
    },
    locate: true,
    src: './test/fixtures/code_128/image-013.jpg',
}, function(result) {
    if (result.codeResult) {
        console.log('result', result.codeResult.code);
    } else {
        console.log('result not detected');
    }
});
```
In this case image-013.jpg was the FSS-10-15-213 barcode with 25pixels of whitespace on each side.

I do have an issue open for surrounding the detected barcode area, and/or the entire image with whitespace before attempting to decode it, but it's not something I have time to get to in the very near future.

Does that help you find a way to work with it?  Or are there other barcodes that are reading incorrectly or not at all?

**Comment by chenyong** [comment]
Thanks for confirmation. At least the encode GS1-128 is supported. We tested more image, it's probably the images looks too fuzzy when there are too many strokes.

**Comment by ericblade** [comment]
No problem :) If you come up with anything more specific that indicates a problem somewhere, please let me know :) I do hope to improve detection in the future, but I do have my hands rather full with making the code modern and more extendable right now.
