### ISSUE TITLE
investigate qrcode reading? possible working fork with qrcode capability

### ISSUE THREAD

**Issue by ericblade** [ericblade/quagga2#21]
Looks like the very first fork that I poked at hit some pay-dirt, here:

https://github.com/z-funfan/quaggaJS/commit/5798cd3f0c86936f97236bce11a2433a23c65f8d

**Comment by ericblade** [comment]
here's another repo that has also implemented qr code reading https://github.com/Louvet/quaggaJS/commit/01b75d545353c8381fe3f54ef538bde9802ee6e3

**Comment by ericblade** [comment]
https://github.com/TomasHubelbauer/js-qr-scanner-library-comparison

**Comment by ericblade** [comment]
I have implemented a very minimal test for the ability to do this as https://github.com/ericblade/quagga2-reader-qr

it probably only works in node, would need additional support to be able to handle browser, and probably could use a bunch of work, but it *is* functional at least to the point where it reads the test png included with it.

**Comment by DanielRuf** [comment]
The zxing library supports QRCode and Data Matrix. How can we support this in this library?

**Comment by ericblade** [comment]
@DanielRuf if you look at  https://github.com/ericblade/quagga2-reader-qr you can see an example of how to pass the image quagga picks up to an external library.  There could probably be ways of improving upon this, but I haven't really thought of them yet. :-) 

Please feel free to ask further questions!
