### ISSUE TITLE
Dist folder is not present

### ISSUE THREAD

**Issue by BRoz** [ericblade/quagga2#219]
I think it could be useful to upload also the compiled version for easy deploy to the web

**Comment by ericblade** [comment]
Hi!  Please comment further on issue #42 as to what exactly you'd like to see.  I am definitely not putting the dist into the source code repo, as built code does not belong in the source repo.  If we can automate adding a build zip to the github Releases page, then I'm all for that, but I don't really have the knowledge of Github Actions to make that happen, and I don't have the time to figure it out, so if that's something you do know, i'd love to hear about it.

In the meantime, I would suggest ```npm install @ericblade/quagga2``` then copying node_modules/@ericblade/quagga2/dist/quagga.js to wherever you're serving it from

**Comment by BRoz** [comment]
Yes, i did it like that, but most inexperienced guys don't know how to do that.
I am too not aware of github actions, but will try to help!

**Comment by Adi-18** [comment]
I also don't know how to do that. So please give provide the compiled version.
