### ISSUE TITLE
Using method decodeUrl only returns "Box" propriety

### ISSUE THREAD

**Issue by danisss9** [ericblade/quagga2#236]
Hello,

I have been using Quagga for LiveStream barcode reading and has been working fine. But I tried now using the **decodeSingle()** method and it doesn't return the decoded code, only the "Box" propriety:

![Result](https://user-images.githubusercontent.com/36733433/93205062-1846ed80-f74f-11ea-91d0-08ae70c2013d.png)

This is the config I'm using (imageUrl is usually a DataUrl):

![Config](https://user-images.githubusercontent.com/36733433/93205171-49bfb900-f74f-11ea-8d44-10630133a840.png)

Why doesn't it return the decoded "result" propriety like it does on "LiveStream" mode? Am I missing something in the config?

Thank you

**Comment by danisss9** [comment]
Seems to be working now, without any changes

**Comment by ericblade** [comment]
Good to know that Data URI works, I believe we had an outstanding ticket to examine that.  Yes, we do, it's #189 .  Any chance you've tried Data URI in the browser?  I'm going to ping you over on that thread to reply to this question actually.

As to why it only returned a partial result, all I can think of is that it found a box, but failed to decode the barcode, but I don't know that that should be an expected result.  

If you can repeat it not working, then working, with any specific data, please definitely report on that.

**Comment by edcsquared** [comment]
Hello, I got same issue regarding on the results. It's only returning [{box: []}], there's no code or something. Am I missing something? thanks

**Comment by ericblade** [comment]
> Hello, I got same issue regarding on the results. It's only returning [{box: []}], there's no code or something. Am I missing something? thanks

hi! i'd probably need some images of the barcodes in question to try to diagnose.  Usually the configuration parameters can be adjusted to find something that works for your specific needs.  Please submit a new issue, with at least one or more images of the barcode in question, along with the type of barcode that it is.  Thanks!

**Comment by edcsquared** [comment]
Thanks for your response @ericblade , here's the issue https://github.com/ericblade/quagga2/issues/537#issuecomment-2078758590. Thanks
