### ISSUE TITLE
QR Code?

### ISSUE THREAD

**Issue by suriyaJaay** [ericblade/quagga2#240]
@ericblade any idea to support QR code scanning?

**Comment by ericblade** [comment]
Hi, you could try https://github.com/ericblade/quagga2-reader-qr 

I know it works for single images, I do not know if it works on live decoding.  I kind of got sidetracked by tracking down all the problems it exposed by adding it, the conversion to typescript, and more recently life in general.

**Comment by UsernameIsReallyNotAlreadyTaken** [comment]
I can confirm it works like a charm for live streams. Make sure to set locate: true.

**Comment by ericblade** [comment]
@suriyaJaay anything further i can help with here?
