### ISSUE TITLE
Other Media Source / Camera

### ISSUE THREAD

**Issue by Juphex** [ericblade/quagga2#241]
Hey, 
is it possible to use another Media/Picture source ?

I use capacitor for camera access.

**Comment by ericblade** [comment]
Sure.  I have no idea what Capacitor is, or what it outputs, but if you can get to an image, then you should be able to either point at it with a file or data URI, and use Quagga.decodeSingle() to point at that.

You might have a look at https://github.com/ericblade/quagga2/blob/master/example/file_input.js .. although that code is before me, so I'm not real sure i'd be able to answer too much about it.  It looks like it creates a file input box in browser, uses the given file to create an image element in HTML, then uses canvas.toDataURL to convert that to a Data URI and passes it to Quagga.

**Comment by ericblade** [comment]
@Juphex anything further that i can help with here?

**Comment by Juphex** [comment]
@ericblade , no thanks:)
