### ISSUE TITLE
Switching cameras | What does Quagga.CameraAccess.release() do?

### ISSUE THREAD

**Issue by ricocynthia** [ericblade/quagga2#253]
Hi!

This isn't necessarily an issue just a question about a few things. 
1) I was looking at the `Quagga.CameraAccess` functions and noticed there is `release()` method. Just curious, what does this do? Does this stop the previous camera session? If that is the case, would I call this function before changing/updating anything in the `inputStream`  (e.g `constraints.width` and `constraints.height`)? I tried looking at the examples in the repo but couldn't seem to find it being used in the live stream example and I couldn't find much documentation about it either. 
2) I'm looking to create a camera drop down (like in the live stream example in this repo), but I'm not sure what is the best way to change the `deviceId` in the `inputStream` when the user selects a different camera. Similar to the question above, would I just stop the previous quagga session (by calling `Quagga.CameraAccess.release()` or `Quagga.stop()`) and then call `Quagga.init()` with the updated `inputStream`?

Thanks in advance!

**Comment by ericblade** [comment]
Good question!

If you call Quagga.stop() that will eventually call CameraAccess.release().  So, I believe a good way to do a switch, is to call Quagga.stop() then call Quagga.init() again with the new deviceId in the constraints.    It might be possible to actually change the camera device on the fly, but I haven't done any research into how that might be achieveable.


CameraAccess.release() calls stop() on the media track associated with the camera video, but calling it alone would not stop Quagga from trying to process (although I have no idea if it would just process an empty image, or if it would generate a bunch of runtime errors)
