### ISSUE TITLE
Demos not working in Chrome for Android or other browsers in android

### ISSUE THREAD

**Issue by npsantini** [ericblade/quagga2#255]
I've been using quaggajs for a while now and all of the sudden it doesn't work on mobile versions of chrome. I believe this could be a relatively new issue, but it could be a few months old.

I'm using the latest version of Chrome for Android and I'm on Android version 10.

Is there a known fix for this or has anyone else run into this problem?

**Comment by ericblade** [comment]
Hi @npsantini !  My phone just updated Chrome yesterday, 86.0.4240.75, and my application seems to be working as normal.

**Comment by suparpat** [comment]
Facing this issue too when using live stream on Android -- image appears for a second then just turns black. Downgrading back to Chrome v80 or use Microsoft Edge works though.

**Comment by ericblade** [comment]
Any chance this is related to Android 11 ?  https://github.com/ericblade/quagga2/issues/266

I am not able to repro using the most recent Chrome update on my Android 9 phone, and that's the best I've got access to.

**Comment by npsantini** [comment]
The devices I'm using are on Android 10. I would share the link, but we have the project limited to specific IP addresses.

**Comment by ericblade** [comment]
@suparpat that's a bit of a long example for me to digest all at once, any chance you can simplify further?  

@npsantini hmm.  android 9 doesn't seem to be having any issues here, with latest chromium available there.  At least not with any of my app code.  I'm.. not sure how to proceed.

**Comment by ericblade** [comment]
... I did not mean to close this.

**Comment by npsantini** [comment]
@ericblade I have done some testing on a few other devices and it does appear to be an Android version problem. It works on Android 9, but not Android 10. All other devices I've tested seem to work fine included chrome for desktop on windows, iphone 14.2 in safari, and ipad os 14.1.

**Comment by npsantini** [comment]
@ericblade The beta demos do seem to work in Chrome on Android 10. The live stream pulls up the front facing camera.

What would be the difference that causes the beta examples to work, but not the other non-beta demos?

**Comment by ericblade** [comment]
@npsantini good question. i didn't even realize there was a "beta" branch in the old repo, until loooooooooooong after i forked.  Might be worth doing a diff on the beta branch. 

I.. don't know when i might have time to do that, things are pretty wild right now.

**Comment by brada1703** [comment]
Has anyone been able to resolve this issue? I'm having problems on Android Version 9... which seems to be working for you guys 🤔

**Comment by ericblade** [comment]
having not received any reports of obvious Android issues in a year now, I'm thinking this problem was resolved in a Chrome update.  If anyone has an issue, lmk, open a new ticket. thanks!
