### ISSUE TITLE
No /dist folder

### ISSUE THREAD

**Issue by kellyjonbrazil** [ericblade/quagga2#264]
Sorry I'm a little new to this but I've been using the upstream QuaggaJS library and would like to try this one out, but I don't see the /dist folder where I can grab the `quagga.min.js` file. Do I need to build this?

Thanks!

**Comment by ericblade** [comment]
You can use npm to install it (````npm install @ericblade/quagga2````) and copy it out of the node_modules/@ericblade/quagga2 dir, or build it from source with ````npm run build````.  I do have a task to figure out how to copy that automatically over to the "Releases" tab on github, but haven't had time to figure that out yet.

**Comment by kellyjonbrazil** [comment]
That worked, thanks!

**Comment by ericblade** [comment]
No problem. It is not included in the repo because the repo is the place for source code, not the minimized versions.

Enjoy!
