### ISSUE TITLE
upgrade to webpack v5, webpack-cli v4

### ISSUE THREAD

**Issue by ericblade** [ericblade/quagga2#271]
... looks like there's some issues to be resolved there.

**Comment by ericblade** [comment]
done in 2.0 branch

**Comment by keithbrink** [comment]
@ericblade Could this be re-opened? I think the 2.0 branch is not destined to be used as far as I can tell, and it would be nice to upgrade to webpack 5. 

Specifically, webpack 4 causes Content Security Protocol violations because it uses eval. Would be great to get rid of those.
