### ISSUE TITLE
investigate how to use correctly without webpack using native browser module import?

### ISSUE THREAD

**Issue by ericblade** [ericblade/quagga2#28]
Seems that there may be some issues with attempting to use quagga with native browser import.

**Comment by ericblade** [comment]
surely, there must be some sort of output setup for webpack to produce a module, but i haven't been able to come up with it with about 30 minutes of searching.  

... ok, after a little while longer searching, it seems that perhaps a webpack upgrade is necessary (or at least desired to be up to date!).. anyway.. webpack might? be able to package a proper module.. possibly need to adjust some babel settings as well.

something involving webpack.config.js { output { library } } .. i'm not sure if there also needs to be babel configuration changes made as well.

The node builder sets BABEL_ENV=commonjs and BUILD_ENV=node and supplies a separate configuration to webpack.  

that could be a strategy to get babel/webpack to generate a js module export.

**Comment by DanielTurner** [comment]
@ericblade you might find rollup config might be easier and there may be useful information here: https://open-wc.org.
Plus if you join the polymer slack channel you should be able to get some help.

**Comment by ericblade** [comment]
Thanks for the tips. I am hoping that someone who has some experience with making a sizeable codebase that was built prior to modules being useful natively in browser, actually work as a regular module will pop in and offer some assistance, before I end up getting to that task myself. :-D  I've got a lot on my plate, and improvements to the existing code are way higher priority than adding another way to use it, right now.  But I would love to have it work as a native module!

**Comment by ericblade** [comment]
closing this, as we're moving towards typescript, so the typescript / webpack output should be a proper module, rather than figuring out if it's possible/proper to be able to straight up import the source directory..
