### ISSUE TITLE
iOS 14.3 beta may include getUserMedia in WebView -- allowing operation in 3rd party browsers and packaged apps?

### ISSUE THREAD

**Issue by ericblade** [ericblade/quagga2#283]
https://twitter.com/webkit/status/1330968468603039744

I have absolutely no way of testing this -- but if anyone's on the beta test for iOS 14.3, i'd love if you could give some things a try?

**Comment by Tielr** [comment]
Hello, 
I installed iOS 14.3 beta 2 on my iPad and was able to scan a bar code from the Chrome browser using this live stream demo: 
https://serratus.github.io/quaggaJS/examples/live_w_locator.html

**Comment by ericblade** [comment]
Wow! That's fantastic news!  

Thank you so much.  If anyone is out there wanting to try it with a PhoneGap (or whatever that's called now) packaged app, that'd be great to hear about too.
