### ISSUE TITLE
iphone xr screensizing problem

### ISSUE THREAD

**Issue by tekspacedemo** [ericblade/quagga2#287]
Hi,

I came across `Quagga` for barcode scanning and created a MVP product to test the functionality. It works great in desktop, but when I try to use it in iPhone the video size of the camera view in model doesnt fit the screen. I have a [codepen](https://codepen.io/raymak/pen/KKgdojM) where I was able to reproduce from iPhone iOS 14 safari browser. Since I dont have mac, I cant open iPhone emulator to test this so wanted to check if you all knows how to fix this?

Here is how it looks when model is opened. 

![92AC6802-A105-424F-BC30-1D0A407B0F56](https://user-images.githubusercontent.com/72271557/100912020-f7fd1400-349d-11eb-89be-6e9b5c331b8a.png)

**Comment by ericblade** [comment]
Adjust your aspectRatio constraint -- it appears that iOS will now give you any aspect ratio you ask for, even if it's pretty much impossible.   If you want a specific aspect ratio you might try like 16/9 or 4/3 something along those lines.  seems like sane values would range between 1 and 16/9 (1.7-ish) or so.

Can you tell me where you picked up that aspectRatio max 100 ?  I'm trying to stomp all of those occurences out of existence so it doesn't continue to spread.

Thank you!

**Comment by tekspacedemo** [comment]
Thanks @ericblade for your quick response.

I followed guide from [here](https://a.kabachnik.info/a-javascript-barcode-reader-with-bootstrap-3-and-quaggajs.html). I didnt realized I had to change the aspectratio. I will change that and give it a try.

**Comment by ericblade** [comment]
Thanks for the link, I have commented to the author to hopefully try to fix it.  Some examples out there in the wild have that, and i've been trying to get them all fixed.. :-D  It's spread around enough that I'm sort of thinking about adding a check for that in the library and specifically throwing out a value of 100 lol

**Comment by tekspacedemo** [comment]
Thank you. I was able to fix the problem by setting max value to 1 and it fix the screen perfectly. :)

**Comment by ericblade** [comment]
if you're going to use that setting at all, a normal value might be 4 / 3 or 16 / 9, or something like that.
