### ISSUE TITLE
autofoucs and manual focus 

### ISSUE THREAD

**Issue by kevintunchan17** [ericblade/quagga2#305]
Hi, I have a question about  `focusMode: 'containous',` that is it possible to set the autofocus and also manual focus (touch and focus like on mobile phone camera app) at the same time? So, I can touch on the mobile screen to focus on the barcode manually because sometimes I have difficulties to focus even I set `focusMode: 'containous'. 
thanks

**Comment by ericblade** [comment]
It is unclear to me if Chromium or any other browser presently supports any focusMode settings in constraints, or anywhere else.

The working draft for these options was last updated just about a month ago https://w3c.github.io/mediacapture-image/

As far as I'm aware, all browsers default to auto-focus on, for camera devices that support auto-focus, and of course off, to any device that doesn't have auto focus.

**Comment by ericblade** [comment]
By the way, here's a little bit of explanation as to how it might work if/when it ever gets implemented into the browsers https://stackoverflow.com/questions/60188128/tap-screen-to-trigger-autofocus-with-getusermedia

**Comment by ericblade** [comment]
I'm going to move this over into discussions

**Comment by ericblade** [comment]
Moving to discussion, until this becomes some sort of a possible feature
