### ISSUE TITLE
Handling multiple barcodes in a single image

### ISSUE THREAD

**Issue by jmcelfresh** [ericblade/quagga2#308]
My application scans book barcodes, which often have more than one barcode closely grouped together.

When Quagga encounters multiple barcodes in a static image it returns a `boxes` object with the boxes for each code detected. It seems like I should be able to call Quagga.decodeSingle again with one of the boxes, but I can't find a way to do this anywhere in the documentation.

Is it possible to specify a box when decoding a barcode from a static image? Or maybe the author intended us to use canvas to cut the barcode out of the image ourselves?

Finally, I can see that the boxes object contains 4 points, does anyone know what units these are in? They are decimal numbers and based on the size of my image and the values it does not appear they are pixels.

Thanks.

**Comment by ericblade** [comment]
I do not, right off hand, know what those are for sure, but my guess is that it's probably corner coordinates, as i'm pretty sure that the visual examples in the repo pass those to the draw functions to draw boxes.  

There is not a way to tell it to decode a specific area of an image, but that might be a handy suggestion for future improvement, if you'd like to start a topic for it.

There is, however, a "multiple" boolean that you can set to true, and it will continue decoding after the first successful find.

> The multiple property tells the decoder if it should continue decoding after finding a valid barcode. If multiple is set to true, the results will be returned as an array of result objects. Each object in the array will have a box, and may have a codeResult depending on the success of decoding the individual box.

**Comment by jmcelfresh** [comment]
Thanks for replying, using `multiple` makes a lot more sense than what I was suggesting.

I looked into the units of the values in `boxes` and they do appear to be pixels. I didn't realize Quagga resizes the image before decoding.
