### ISSUE TITLE
Export reader types

### ISSUE THREAD

**Issue by mquinn-leverege** [ericblade/quagga2#313]
Now that it is possible to register your own readers, would you consider exporting the internal reader classes so that they can be extended? I find that in some cases, Code 39 VIN barcodes are inverted and aren't detected by Quagga unless I invert the colors of the image I am feeding it. It might be really handy for me to be able to extend the VIN reader and invert my data before decoding.

**Comment by ericblade** [comment]
Hi ! Sorry it took me a long time to get back on this, have had Internet issues the last several days. 

You'd like to add an export of all the readers, perhaps as Quagga.Readers ?  I would be willing to entertain a pull request for that, for sure.  

Something I think I'd like to do in a future major upgrade, is separate the Readers from the main, but I haven't had a look at doing any of that.  So, short term, your suggestion does sound like it would be a good idea, and might make it easier to work on improvements to the readers, without digging into the entire code.

I'd be interested in seeing the results of what you come up with with your VIN reader enhancements, I wonder if it might be applicable to any others, too?

**Comment by ericblade** [comment]
ping @mquinn-leverege 

i probably have some time to actually implement this now, just wanting to confirm that i understand the request correctly

**Comment by mquinn-leverege** [comment]
Very sorry! Yes, that's all I was talking about was to add the readers as an export item such as `Quagga.Readers`. Would have created the PR but work took a different course soon after I opened this issue.

**Comment by ericblade** [comment]
Implemented in 1.4.0
