### ISSUE TITLE
drawingBuffer canvas should probably be inside the video element, not below

### ISSUE THREAD

**Issue by ericblade** [ericblade/quagga2#33]
CSS positioning is a nightmare.  It works much easier having the drawingBuffer canvas inside the video element, so it inherits the same box.

As Quagga does support sending in a previously created container, as well as giving it a proper video and canvas element (as well as a "imgBuffer" tagged canvas, which I'm not sure what that is used for just yet), I'm using a sample that looks like

````
            <div className={css.scannerContainer} ref={scannerRef}>
                <video style={{width: window.innerWidth, height: 480}}>
                    <canvas className="drawingBuffer" width="640" height="480" />
                </video>
                <Scanner scannerRef={scannerOpen && scannerRef} onScannerReady={onScannerReady} onDetected={() => console.warn('* onDetected')} />
            </div>
````

This allows me to get proper canvas positioning, without having to resort to bizarre CSS tricks, so I'm pretty sure that this should be the default method for creating it when you don't provide a custom video and canvas element

**Comment by ericblade** [comment]
doesn't work from inside the video tag.  still going to leave this open because I think that the hierarchy needs some work so this will remind me to look at it.

**Comment by ericblade** [comment]
Also noting: investigate where debug drawing is going to, see #54

**Comment by coolcorey** [comment]
Not sure if this helps but, I ended up wrapping the video and canvas elements in a div with position: relative, and then set position: absolute, top: 0 on the canvas to overlay them.

**Comment by ericblade** [comment]
yep.. that is what i came up with, too, thanks for confirming.  i'm not entirely positive that i want to enforce that inside quagga, but i think i do, if you don't provide an element of your own.

**Comment by ericblade** [comment]
per discussion on #151 I think is the better option -- if you want a drawingBuffer, then specify it yourself in your HTML/CSS setup, we'll search for it, but it shouldn't be created for you.

**Comment by kellyjonbrazil** [comment]
@coolcorey Sorry, but for the novices could you provide a simple example of how you got this working? Right now I'm just using something like this:

```
<style>
        canvas.drawing, canvas.drawingBuffer {
            position: absolute;
            left: 0;
            top: 0;
        }
</style>

<div id="scanner-container"></div>

<script>
      function startScann...
```

Which obviously doesn't work when the "scanner-container" div is not at the top left corner of the window.

**Comment by ericblade** [comment]
if you relatively position the scanner-container, then the absolute positioned elements inside it will be positioned with 0,0 in the upper left of the div, not the screen, it would seem.  And now that significantly improves my understanding of why certain things work and why certain things don't!

https://css-tricks.com/absolute-positioning-inside-relative-positioning/
