### ISSUE TITLE
Quagga.CameraAccess.enumerateVideoDevices() Missing Items?

### ISSUE THREAD

**Issue by chobo2** [ericblade/quagga2#352]
Hi

I finally got hold of an iphone (iphone 6) and been testing my application. I have a dropdown that should hold all different video devices but my list is always empty as I get 1 video device back and it has no "deviceId" or "label" both are blank.

I tried the live stream example and it is getting the same thing. Is this to be expected on iphones? Or just old Iphones?

The weird thing is the library can see to handle it, as the camera still loads even though I am doing it all by deviceId, so I guess it still matching the blank device id with the one on the phone.

**Comment by chobo2** [comment]
Also getting blank list on Samsung A70

**Comment by chobo2** [comment]
maybe it is my code?

    Quagga.CameraAccess.enumerateVideoDevices().then(function (devices) {
      
      var deviceId = determineCamera(devices);
      setupQuagga(deviceId);
      setupCameraSelectList(devices, deviceId);
    });


```
  function setupCameraSelectList(devices, defaultDeviceId) {
    devices.forEach((device) => {
      if (device.deviceId !== "default") {
        var selected = defaultDeviceId == device.deviceId;
        if (selected) {
          $("#cameras-selection").append(
            `<option value="${device.deviceId}" selected="selected">${device.label}</option>`
          );
        } else {
          $("#cameras-selection").append(
            `<option value="${device.deviceId}">${device.label}</option>`
          );
        }
      }
    });
  }
```

**Comment by chobo2** [comment]
I have also tried to use the example code which seems to have a bit better chance of populating the dropdown but I still am not getting it filled.

```
  function setupCameraSelectList(devices, defaultDeviceId) {
    var streamLabel = Quagga.CameraAccess.getActiveStreamLabel();
    Quagga.CameraAccess.enumerateVideoDevices().then(function (devices) {
      devices.forEach(function (device) {
        var selected = streamLabel === device.label;
        if (selected) {
          $("#cameras-selection").append(
            `<option value="${
              device.deviceId || device.id
            }" selected="selected">${pruneText(
              device.label || device.deviceId || device.id
            )}</option>`
          );
        } else {
          $("#cameras-selection").append(
            `<option value="${device.deviceId || device.id}" >${pruneText(
              device.label || device.deviceId || device.id
            )}</option>`
          );
        }
      });
    });
  }
```

**Comment by ericblade** [comment]
could you post the output of 

navigator.mediaDevices.enumerateDevices().then(x => console.log(x))

on the device in question?  
perhaps followed by

Quagga.CameraAccess.enumerateVideoDevices().then(x => console.log(x))

so we can see what it's getting, and what's happening to it?

**Comment by chobo2** [comment]
> could you post the output of
> 
> navigator.mediaDevices.enumerateDevices().then(x => console.log(x))
> 
> on the device in question?
> perhaps followed by
> 
> Quagga.CameraAccess.enumerateVideoDevices().then(x => console.log(x))
> 
> so we can see what it's getting, and what's happening to it?

Yeah that is a bit hard as  I don't have a mac so can't connect it to anything to see the console.log lines, I had to alert box everything.

I think I figured out the reason though not sure what is the best way to solve it. 

Basically it seems like you first need to get permission from the camera to get full information on some devices especially mac stuff.

I was doing Quagga.CameraAccess.enumerateVideoDevices() this first as I wanted to get a deviceId to pass into the Quagga. My plan was to find anything that was labeled "back" and then use that as the default camera instead of depending on "environment".

But since I got to load up the camera first to ensure I can get all of the deviceID's back I am stuck to using Environment again and having them manually chose their camera based on a dropdown.

**Comment by ericblade** [comment]
Aha! Permissions issues.  Chrome on Android also has permissions issues -- you can't see the list of cameras until after you've granted permissions to the site, but you can't get permission until you actually try and use the camera.  Desktop Chrome does *not* have this problem, and it asks you for permission as soon as you try to query the list.

I solved that by running this at app startup

````
const preInitMiddleware: Middleware = (store: MiddlewareAPI) => (next) => async (action) => {
    switch (action.type) {
        case appPreInit.type:
            await Quagga.CameraAccess.request(null, {});
            await Quagga.CameraAccess.release();
            store.dispatch(enumerateVideoDevices());
            break;
        default:
            break;
    }
    next(action);
};
````
(this is a redux action that my app dispatches the moment it's loaded)

**Comment by chobo2** [comment]
> Aha! Permissions issues. Chrome on Android also has permissions issues -- you can't see the list of cameras until after you've granted permissions to the site, but you can't get permission until you actually try and use the camera. Desktop Chrome does _not_ have this problem, and it asks you for permission as soon as you try to query the list.
> 
> I solved that by running this at app startup
> 
> ```
> const preInitMiddleware: Middleware = (store: MiddlewareAPI) => (next) => async (action) => {
>     switch (action.type) {
>         case appPreInit.type:
>             await Quagga.CameraAccess.request(null, {});
>             await Quagga.CameraAccess.release();
>             store.dispatch(enumerateVideoDevices());
>             break;
>         default:
>             break;
>     }
>     next(action);
> };
> ```
> 
> (this is a redux action listener that my app dispatches the moment it's loaded)

Since it is mixed a with redux stuff it is a little bit confusing to me. But basically you need to call  these first? 

      await Quagga.CameraAccess.request(null, {});
       await Quagga.CameraAccess.release();

Then call enumerateVideoDevices()  and init() after?

This is what I have so far so would I just put those 2 lines before my init() call?

```
$(function () {
  init(); // call the above 2 lines before this? I maybe have to use the old .then() way instead of async/await not sure what browser requirements are right now.

  $("#cameras-selection").change(function () {
    var optionSelected = $(this).find("option:selected");
    var deviceId = optionSelected.val();

    Quagga.stop();

    setTimeout(function () {
      setupQuagga(deviceId);
    }, 50);
  });

  function startCamera() {
    Quagga.start();
  }

  function printObject(o) {
    var out = "";
    for (var p in o) {
      out += p + ": " + o[p] + "\n";
    }
    alert(out);
  }

  function setupCameraSelectList() {
    var streamLabel = Quagga.CameraAccess.getActiveStreamLabel();

    Quagga.CameraAccess.enumerateVideoDevices().then(function (devices) {
      devices.forEach((device) => {
        function pruneText(text) {
          return text.length > 30 ? text.substr(0, 30) : text;
        }
        if (device.deviceId !== "default" && device.id !== "default") {
          var selected = streamLabel == device.label;
          if (selected) {
            $("#cameras-selection").append(
              `<option value="${
                device.deviceId || device.id
              }" selected="selected">${pruneText(
                device.label || device.deviceId || device.id
              )}</option>`
            );
          } else {
            $("#cameras-selection").append(
              `<option value="${device.deviceId || device.id}">${pruneText(
                device.label || device.deviceId || device.id
              )}</option>`
            );
          }
        }
      });
    });
  }

  function setupQuagga(deviceId) {
    Quagga.init(
      {
        inputStream: {
          name: "Live",
          type: "LiveStream",
          target: "#container",
          constraints: {
            width: { min: 640 },
            height: { min: 480 },
            facingMode: "environment",
            deviceId: deviceId,
          },
        },
        decoder: {
          readers: ["upc_reader", "ean_reader"],
        },
      },
      function (err) {
        if (err) {
          console.log(err);
          return;
        }

        startCamera();
        setupCameraSelectList();
      }
    );
  }

  function determineCamera(devices) {
    var backDevices = devices.filter(function (device) {
      return device.label.includes("back");
    });

    var constraints;
    if (backDevices.length > 0) {
      return backDevices[0].deviceId;
    } else if (devices.length > 0) {
      return devices[0].deviceId;
    }

    return -1;
  }

  function init() {
    $("#cameras-selection").empty();

    Quagga.CameraAccess.enumerateVideoDevices().then(function (devices) {
      var deviceId = determineCamera(devices);
      setupQuagga(deviceId);
    });
  }

  var lastResult = "";
  Quagga.onDetected(function (result) {
    var code = result.codeResult.code;
    
    if (lastResult !== code) {
      lastResult = code;

      var countDecodedCodes = 0,
        err = 0;
      $.each(result.codeResult.decodedCodes, function (id, error) {
        if (error.error != undefined) {
          countDecodedCodes++;
          err += parseFloat(error.error);
        }
      });
      if (err / countDecodedCodes < 0.1 && sanityCheck(code)) {
        $(".search-box").val(result.codeResult.code);
      }
    }

    function sanityCheck(s) {
      return s.toUpperCase().match(/^[0-9A-Z\s\-\.\/]+$/);
}

    // if (result.codeResult) {
    //   $(".search-box").val(result.codeResult.code);
    //   //  hideCamera();
    // }
  });

  Quagga.onProcessed(function (result) {
    var drawingCtx = Quagga.canvas.ctx.overlay,
      drawingCanvas = Quagga.canvas.dom.overlay;

    if (result) {
      if (result.boxes) {
        drawingCtx.clearRect(
          0,
          0,
          parseInt(drawingCanvas.getAttribute("width")),
          parseInt(drawingCanvas.getAttribute("height"))
        );
        result.boxes
          .filter(function (box) {
            return box !== result.box;
          })
          .forEach(function (box) {
            Quagga.ImageDebug.drawPath(box, { x: 0, y: 1 }, drawingCtx, {
              color: "green",
              lineWidth: 2,
            });
          });
      }

      if (result.box) {
        Quagga.ImageDebug.drawPath(result.box, { x: 0, y: 1 }, drawingCtx, {
          color: "#00F",
          lineWidth: 2,
        });
      }

      if (result.codeResult && result.codeResult.code) {
        Quagga.ImageDebug.drawPath(
          result.line,
          { x: "x", y: "y" },
          drawingCtx,
          { color: "red", lineWidth: 3 }
        );
      }
    }
  });
});

```
I also put false positively rate check on "onDetected" as again was not sure how your sample code you posted to me would be incorporated into a jquery/vanilla javascript project, so i you could help me on that as well it would be greatly appreciated.

**Comment by chobo2** [comment]
this is what I added with the release and request ones.

```
 Quagga.CameraAccess.request(null, {}).then(function() {
    Quagga.CameraAccess.release().then(function() {
      Quagga.CameraAccess.enumerateVideoDevices().then(function (devices) {
        init(devices)
      });
  
    })
  });
```

**Comment by ericblade** [comment]
yes, my app does not immediately start the camera, so i can await a request/release to trigger Android Chrome (and i guess Safari) to ask for permissions first, then do enumerateVideoDevices() and store that in a list, then when the user opens Settings (or I guess Camera, if it's not set) then they can pick which device to use.

the code in the other thread for throwing out UPC code errors should be pretty much plug-in, just run it in your onDetected.  It's pretty messy code, but it's complete. :)

**Comment by chobo2** [comment]
> yes, my app does not immediately start the camera, so i can await a request/release to trigger Android Chrome (and i guess Safari) to ask for permissions first, then do enumerateVideoDevices() and store that in a list, then when the user opens Settings (or I guess Camera, if it's not set) then they can pick which device to use.
> 
> the code in the other thread for throwing out UPC code errors should be pretty much plug-in, just run it in your onDetected. It's pretty messy code, but it's complete. :)

ok, I think what I wrote with my 3 thens is correct?

What do I put in the OnDetected? both what you wrote are functions? Do I just call the getMedianOfCodeErrors() and pass it in "result" from onDetected?

**Comment by chobo2** [comment]
> yes, my app does not immediately start the camera, so i can await a request/release to trigger Android Chrome (and i guess Safari) to ask for permissions first, then do enumerateVideoDevices() and store that in a list, then when the user opens Settings (or I guess Camera, if it's not set) then they can pick which device to use.
> 
> the code in the other thread for throwing out UPC code errors should be pretty much plug-in, just run it in your onDetected. It's pretty messy code, but it's complete. :)

barcodeValidator part of the other library you have? Can it be used without typescript and just a regular js reference?

**Comment by ericblade** [comment]
yeah npm install @ericblade/barcode-validator, you get the javascript library.  

UPC-A and EAN-13 are the same thing https://www.nationwidebarcode.com/are-upc-a-and-ean-13-the-same/

You could use it without the barcode-validator package, just remove the references to it, but i find that using it strikes a good balance between speed and accuracy for at least my Motorola G Stylus. I do occasionally get some read errors but not nearly as many as before adding the checks to it.

**Comment by chobo2** [comment]
> yeah npm install @ericblade/barcode-validator, you get the javascript library.
> 
> UPC-A and EAN-13 are the same thing https://www.nationwidebarcode.com/are-upc-a-and-ean-13-the-same/
> 
> You could use it without the barcode-validator package, just remove the references to it, but i find that using it strikes a good balance between speed and accuracy for at least my Motorola G Stylus. I do occasionally get some read errors but not nearly as many as before adding the checks to it.
> 
> (if you give me a few EAN barcodes, I can make sure it works with them...)

I am not using npm, just regular JavaScript references. Does the npm package just contain a single .js file?

Yeah they are similar but not sure how it effects your validator.

I don't really have any myself as I am also in North America but I do need to support it.

I did some googling

https://barcode1.com.au/wp-content/uploads/sites/71/2013/09/07-EAN-13-Standard-1.jpg
https://redicode.com.au/wp-content/uploads/2020/01/Redicode-EAN-13.png
https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fwww.computalabel.com%2FImages%2FEAN13%402x.png&f=1&nofb=1
