### ISSUE TITLE
Wrong reading

### ISSUE THREAD

**Issue by daniieljc** [ericblade/quagga2#360]
Good, when I read a barcode sometimes it reads the data incorrectly, especially when the code is of a reduced size, my question is, is there a way to put a kind of delay or a double check on it?

**Comment by ericblade** [comment]
There are many different things that can be done, and I wish I had time to go through and really do some empirical testing to find out what works the best, but there's so many variables....   of course, i'd also love to improve the reader qualities.. but.. limited time.

Here is something I've been using with UPC/EAN codes, I don't know if it applies to other types

https://github.com/ericblade/quagga2/issues/351#issuecomment-822649962

Should probably build a Discussions post with this information.
