### ISSUE TITLE
Installation description is out of date

### ISSUE THREAD

**Issue by attikov** [ericblade/quagga2#386]
Links are broken, folders are missing (dist) etc... 
The installation part from the readme is useless.

**Comment by ericblade** [comment]
No, they're not, and no it's not.

If you have an issue with a specific link, please elaborate, but all the external links I see work.  And the install part is basically just "use npm".

**Comment by attikov** [comment]
Ok,

Why would you check only the external links? Strange. Anyway, here it is:

"You can get the quagga.js file in the following ways:
By installing the npm module and copying the quagga.js file from the dist folder."

<a href="https://github.com/SudhamJayanthi/quagga2#npm">installing the npm module</a>

**Comment by ericblade** [comment]
Thank you for pointing to one that is.  I wasn't going to go through and check every single link in the entire document, it's a pretty sizeable document.  Apologies if my tone comes off harsh, I am re-reading earlier, and I don't intend to be like that :|

So, yes, if you install the npm module you'll have the dist, where you can get the quagga.js file.  or you can build it yourself.

i'll update the link there...

**Comment by attikov** [comment]
All ok, I could also have point it out at the fist time instead of ranting. I'll try it again. thx!
