### ISSUE TITLE
EAN-13 Barcode is not scannable

### ISSUE THREAD

**Issue by Qwoon** [ericblade/quagga2#393]
Hi, we faced the issue, that some ean-13 barcodes are not scannable, even after using the official example of quagga js.
Most of the issue that are posted here (like #392) are working perfectly fine.

Here is the example of an "unscannable" barcode:
![photo_2022-01-26_16-07-00](https://user-images.githubusercontent.com/39094902/151184906-56de85e4-d634-4277-be54-541ec7bff7e8.jpg)

**Comment by ericblade** [comment]
As far as I can tell, this one's not a UPC -- several readers that do decode it say it's a Code128.

The amount of shadows on the right hand side of this image specifically seem to prevent Quagga from decoding it, but it does locate the barcode square until that shadow gets too dark on the right.

I'm pretty confident that if you added code128 to your readers and improved the lighting a bit, that it would find it.

**Comment by ericblade** [comment]
@Qwoon i'm going to close soon if there's no further issue

**Comment by ericblade** [comment]
@Qwoon closing this issue, as there's nothing that I can find here to do on our end.  Please come back to us if there's any further issues/discussion to be had :)
