### ISSUE TITLE
Decoder Multiple Property

### ISSUE THREAD

**Issue by alulsirclo** [ericblade/quagga2#420]
`The multiple property tells the decoder if it should continue decoding after finding a valid barcode. If multiple is set to true, the results will be returned as an array of result objects. Each object in the array will have a box, and may have a codeResult depending on the success of decoding the individual box.`

I tried add multiple property to true, and passed multiple reader type too (ean, upc, and 128). I scan the upc barcode, but it always return single array with ean_13 type instead. Can quagga return all possibility type in that return?
![image](https://user-images.githubusercontent.com/84361839/167393440-8a0544a3-9627-4d18-bdd5-79d20eccade6.png)

**Comment by ericblade** [comment]
Hi there!  Multiple is used to locate and return the results of multiple barcodes within the input image.

UPC is a subset of ean_13, so if you want UPCs specifically you should use the upc reader, but if you want the wider range EAN then you should use that.  

A single barcode object will not be decoded by multiple readers, the first one in the array that returns a positive result will be used.

Does that answer the question adequately?  or have I misunderstood?

**Comment by alulsirclo** [comment]
Understood, thank you so much for your explanation
