### ISSUE TITLE
import types from the library without including it in the webpack builder

### ISSUE THREAD

**Issue by SDAdham** [ericblade/quagga2#421]
Hi team,

I changed the following line from:
```
import Quagga, { QuaggaJSResultObject } from '@ericblade/quagga2';
```
to:
```
import { QuaggaJSResultObject, QuaggaJSStatic } from '@ericblade/quagga2/type-definitions/quagga';
```
to avoid including it in the build, however it's still be included, not sure how can I avoid including it? 
![image](https://user-images.githubusercontent.com/11182824/169502075-9380b2a6-416d-4145-bc37-b15173e3de7d.png)

The reason behind doing this is because I dynamically import it separately rather bundling it within the `vendor.js` to reduce initial loading time and improve the apps performance.

Can you please help?

**Comment by ericblade** [comment]
Hi!  If you're using TypeScript, recent versions add a "import type" capability

```
import { type QuaggaJSResultObject, type QuaggaJSStatic } from ...
```
which would allow you to reference it, and it would be stripped when TSC is done with it.

Otherwise, it sounds like some advanced webpack configuration that I'm afraid I know extremely little about.

**Comment by SDAdham** [comment]
Thanks @ericblade! I did that but it would be there still, so I knew I had to look somewhere else till I learned that I am using https://www.npmjs.com/package/ngx-barcode-scanner which adds it. Moving it's import to the right place helped me solving the problem.

Many thanks! Issue solved.

**Comment by ericblade** [comment]
great to hear!
