### ISSUE TITLE
Tracer does not search in direction of {y-1, x+1}

### ISSUE THREAD

**Issue by TonyKhorouzan** [ericblade/quagga2#439]
In file tracer.js in function trace, the last searchDirection is not used.

Near lines 5 and 18:

```
    searchDirections: [[0, 1], [1, 1], [1, 0], [1, -1], [0, -1], [-1, -1], [-1, 0], [-1, 1]],
    ... omitted code...
           for (i = 0; i < 7; i++) {
                y = current.cy + searchDirections[current.dir][0];
                x = current.cx + searchDirections[current.dir][1];

```
The last element of searchDirections is never used.

The iteration should be:
        
`           for (i = 0; i < 8; i++) {`

or

`           for (i = 0; i <= 7; i++) {`

**Comment by ericblade** [comment]
Excellent find.  I dislike magic numbers, so searchDirections.length it is :)
