### ISSUE TITLE
Error detection for endless loops in Contour Tracing

### ISSUE THREAD

**Issue by TonyKhorouzan** [ericblade/quagga2#440]
For images with a lot of graphics, I find that contourTracing can get in an endless loop, where it encounters an embedded cycle.   I am not sure how the cycle gets created.  I can't be sure the endless loop is not a side-effect of my porting, but if anyone else runs into a similar issue this might be helpful.

Tracer,js function contourTracing, near line 57:

`            if (trace(current, color, label, edgelabel)) {
...omitted code...
                do {`

Can detect/workaround:

```
            let pixelCount = 0;
            let maxPixel = imageDimensions.Width * imageDimensions.Height;
	    if (trace(current, color, label, edgelabel)) {
...omitted code unchanged...
                do {
		    pixelCount++;
                    if (pixelCount > maxPixel)
                    {   /* Error - a cycle of connected points has occurred. */
                        break;
                    }
```

This is not the best error recovery or detection logic, but works for my purposes.

**Comment by ericblade** [comment]
interesting! i have had some occasional lockups on handhelds, and just kind of blamed android for it.  

Any chance you might have an image you could provide that demonstrates the problem?  

Fix seems reasonable, although I'm a bit out of my .. um.. depth.. in this area of the code.  I really appreciate you taking a look through it and reporting your findings, for sure.
