### ISSUE TITLE
Multiple readback operations can be made faster.

### ISSUE THREAD

**Issue by sam-the-programmer** [ericblade/quagga2#459]
Hi there, just working on a Quagga2-based product, and came across this warning in the dev tools. Is there a reason that this is not changed/implemented for performance?

```
Canvas2D: Multiple readback operations using getImageData are faster with the willReadFrequently attribute set to true. [quagga.min.js:3]
```

**Comment by sam-the-programmer** [comment]
Thanks

**Comment by ghevge** [comment]
I'm seeing the same warning on chrome

**Comment by ericblade** [comment]
Curious, I haven't seen it, but I also don't do a lot of chrome debugging with the camera, since my USB cameras don't read barcodes, so I'm usually doing things with my phone, which is a lot harder to hit with the dev tools.  

Does it seem like there's any particular operation that causes it?   When does the message occur? 

I'm thinking it should be easy to just add a config flag, and have that passed along to getImageData, which would allow us to experiment with it without necessarily breaking anything.

**Comment by ghevge** [comment]
It shows up when you open the video stream. The is the error stack while using V 1.7.7

frame_grabber_browser.js:107 Canvas2D: Multiple readback operations using getImageData are faster with the willReadFrequently attribute set to true. See: https://html.spec.whatwg.org/multipage/canvas.html#concept-canvas-will-read-frequently
_that.grab @ frame_grabber_browser.js:107
(anonymous) @ quagga.ts:223
newFrame @ quagga.ts:248
requestAnimationFrame (async)
newFrame @ quagga.ts:250
requestAnimationFrame (async)
newFrame @ quagga.ts:250
requestAnimationFrame (async)
newFrame @ quagga.ts:250
requestAnimationFrame (async)
newFrame @ quagga.ts:250
startContinuousUpdate @ quagga.ts:254
start @ quagga.ts:259
start @ quagga.js:42
(anonymous) @ barcodeReader.js:43
ready @ quagga.ts:55
(anonymous) @ quagga.ts:93
adjustWorkerPool @ qworker.ts:165
(anonymous) @ quagga.ts:85
trigger @ input_stream_browser.ts:123
(anonymous) @ quagga.ts:107
Promise.then (async)
initInputStream @ quagga.ts:107
init @ quagga.js:37
initQuagga @ barcodeReader.js:17
showScan @ barcodeReader.js:10
onclick @ index.html:1

**Comment by ericblade** [comment]
ooh! fantastic, thanks for the backtrace.  I'll try to grab a few minutes this weekend to thread a setting you can put in init to toggle that, then, and we shall see what happens!

**Comment by ericblade** [comment]
did not get to this when i wanted to, have been super busy with work and family having covid :( but will try over the US holiday weekend :)

**Comment by ericblade** [comment]
working on threading this through...

**Comment by ericblade** [comment]
1.8.1 appears to correctly thread this through to the spots where it's used in most instances.  Added willReadFrequently: boolean options to QuaggaJSResultCollector, QuaggaJSConfigObject.inputStream and QuaggaJSConfigObject.locator .

I'm pretty sure you want to add it to inputStream config, possibly also locator.

**Comment by ericblade** [comment]
fwiw, it seems to work fine for my application, on my mobile.  I saw a few other settings in that function that i'll probably wire up similarly
