### ISSUE TITLE
Node js invalid ASM

### ISSUE THREAD

**Issue by caleb-tonkinson** [ericblade/quagga2#467]
Looking at using Quagga for scanning some files and extracting barcode data. I added it to my **express** backend and followed the node example from the repo (thanks for having those).
Everything compiles fine but when I actually run it, it fails with the included error about invalid asm.js.

I have also attempted to use `const Quagga = require("@ericblade/quagga2/lib/quagga").default` but that yielded the same results.
```javascript
import Quagga from "@ericblade/quagga2";
const buffer = fs.readFileSync('target.jpg');
const qRes = await Quagga.decodeSingle({
      src: buff,
      numOfWorkers: 0,
      decoder: {
        readers: ["code_128_reader"], // List of active readers
      },
    });
```
`(node:34759) V8: {...}/node_modules/@ericblade/quagga2/lib/quagga.js:3663 Invalid asm.js: Unexpected token`

Running on node 16.15.

Any thoughts on what the issue could be?

**Comment by caleb-tonkinson** [comment]
Apologies my test image was just bad and had nothing quagga could read 😆

**Comment by ericblade** [comment]
Sorry :) The Invalid asm.js is a known problem message, but it doesn't seem to affect anything -- the asm.js just runs as regular Javascript, so although it might well perform better if it were ocmpiling to asm correctly, it doesn't harm the operation, in any way that I can tell.

I've been trying to find ways to port that old asm.js into wasm, but haven't come up with anything yet.
