### ISSUE TITLE
**** quagga loadImages error: Error: SOI not found

### ISSUE THREAD

**Issue by selected-pixel-jameson** [ericblade/quagga2#473]
Hello,

I'm attempting to use this library to upload an image to an ExpressJS server, and pass in a base64 encoded jpeg or png.  In either case I receive the following error.

**** quagga loadImages error: Error: SOI not found
    at constructor.parse (/Users/..../node_modules/jpeg-js/lib/decoder.js:631:15)
    at Object.decode (/Users/..../node_modules/jpeg-js/lib/decoder.js:1116:11)
    at handleJPEG (/Users/..../node_modules/get-pixels/node-pixels.js:32:21)
    at doParse (/Users/..../node_modules/get-pixels/node-pixels.js:114:7)
    at /Users/..../node_modules/get-pixels/node-pixels.js:146:11
    at processTicksAndRejections (internal/process/task_queues.js:77:11)
 
 Error ---------------------------------------------------
 
  Error: error decoding pixels in loadImages
      at /Users/..../node_modules/@ericblade/quagga2/lib/quagga.js:10718:17
      at handleJPEG (/Users/..../node_modules/get-pixels/node-pixels.js:35:5)
      at doParse (/Users/..../node_modules/get-pixels/node-pixels.js:114:7)
      at /Users/..../node_modules/get-pixels/node-pixels.js:146:11
      at processTicksAndRejections (internal/process/task_queues.js:77:11)

This is the code that I'm using

```
const Quagga = require('@ericblade/quagga2').default
const multer = require('multer')
const storage = multer.memoryStorage()
const upload = multer({ storage: storage })
router.post('/barcode/?', upload.single('image_data'), async (req, res, next) => {
  try {
    const response = {}
    const encoded = req.file.buffer.toString('base64')
    const src = `data:${req.file.mimetype};base64,${encoded}`
    Quagga.decodeSingle({
      src: src,
      numOfWorkers: 0, // Needs to be 0 when used within node
      decoder: {
        readers: [{
          format: 'ean_reader',
          config: {
            supplements: [
              'ean_5_reader', 'ean_2_reader'
            ]
          }
        }]
      }
    }, function (result) {
      if (result.codeResult) {
        console.log('result', result.codeResult.code)
      } else {
        console.log('not detected')
      }
    })
  } catch (error) {
    next(error)
  }
})
```

**Comment by ericblade** [comment]
Hmm. not entirely certain, but my guess would be that the dataurl is malformed .. something along the lines of the mimetype isn't correct to the data, so it reads the wrong thing.  See also https://stackoverflow.com/questions/47448303/soi-not-found-from-saved-canvas-image   .. although I recognize you're not using toDataURL, you are forming a dataURL yourself

**Comment by ericblade** [comment]
@selected-pixel-jameson ?
