### ISSUE TITLE
[Violation] 'requestAnimationFrame' handler took <N>ms

### ISSUE THREAD

**Issue by gpalomar** [ericblade/quagga2#484]
First, nice work @ericblade !

I'm getting this error when usign Quagga with type LiveStream with frequency 20. Could this affect to performance? How can we avoid this warning?

![image](https://user-images.githubusercontent.com/3463553/216093820-20182643-67a2-41b9-a2a6-fde13fbbf65d.png)

Thanks!

**Comment by ericblade** [comment]
that seems to be an indication that it is in fact affecting performance.  I'm honestly not sure about what exactly the frequency parameter represents, if it's a target frames per second, or a demand for frames per second, or what.  

I'd try increasing it by quite a lot and see what happens, if it remains same, then try decreasing it by quite a lot, and see what happens.  

Please report back :) thanks

**Comment by gpalomar** [comment]
I've tried to decrease the frequency to 1 and it still shows the warning, and my handler only has a console.log

**Comment by ericblade** [comment]
ok, so... i just looked into the actual code that runs with requestAnimationFrame .. 

so.. what it does, is it runs a frame update every 1000 / (config.frequency) milliseconds.  if frequency is not there, it is 60.  The samples I inherited with this code use 10.  

so, 1000 / 10 should be updating with 100ms intervals between. captures.

the requestanimationframe function calls update, which calls framegrabber to grab the image, and then locateAndDecode, to attempt to run the locator and the decoder.   
eventually, if anything is located/decoded, it would also pass that into your callbacks, which look like they would be executed in the same run, so this should include the entire locate/decode process, as well as any handlers you have attached to handle detection or successful decode.  

i haven't timed this directly in a browser, but 70-100ms for a complete decode operation seems normal, from what I remember of test runs outputs.

SO .. this seems like it's probably a recent addition to a browser.  What browser/version are you using?  and is it a desktop or a mobile?

**Comment by ericblade** [comment]
please reopen if you have any further input @gpalomar .  I have been unable to reproduce this in anything I use, so I'd need more information to try and chase it down.
