### ISSUE TITLE
Camera window freezes on iPhone/iPad

### ISSUE THREAD

**Issue by cc13com** [ericblade/quagga2#500]
Hello,

I tested with quagga and quagga2 with the same issue. On my Google Pixel 7 all is fine and working as expected. Tested from the browser and installed as an PWA application on my phone.

As soon as I test on iPhone 13 or iPad the reader is working only if I run my "app" in the Safari browser. But if I install the app as a PWA application on the iPhone/iPad the camera window freezes if I run the quagga script. I can see the picture taken from the camera but still frozen. It's not showing the live content.

**Comment by ericblade** [comment]
Sounds very strongly like an iOS problem.  But... what is your configuration you're passing to Quagga.init?  

It wasn't until I think the most recent iOS release that camera was even supported outside of Safari in WebView, and that might still be in beta.. i don't track what's going on with iOS much since I don't have any iOS things

**Comment by cc13com** [comment]
If I remember right it was working on an older iOS/Safari version.

My init/config looks like:

```
init: function(regionID, attribute1, width, height) {
        var self = this;
        regionID = regionID;
        barcodeItem = attribute1;
        l_width = width;
        l_height = height;

        console.log('init: ' + regionID);

        Quagga.init(this.config, function(err) {
            if (err) {
                return self.handleError(err);
            }
            Quagga.start();
        });
    },
    handleError: function(err) {
        console.log(err);
    },
    config: {
        inputStream: {
            target: scannerCamEl,
            type : "LiveStream",
            constraints: {
                // width: {min: l_width},
                width: 320,
                height: 240,
                facingMode: "environment"
                //aspectRatio: {min: 1, max: 2}
            }
        },
        locator: {
            patchSize: "medium",
            halfSample: true
        },
        numOfWorkers: 2,
        frequency: 10,
        decoder: {
            readers : [{
                format: "ean_reader",
                config: {}
            }]
        },
        locate: true
    }
```

**Comment by ericblade** [comment]
hmm.  can you tell if your code is still running?  i'm not sure what on device debugging capabilities th ere are, but I'd presume there's some way to debug on device, and you could get the logs or something to see if it's actually doing anything at all.

It wouldn't surprise me if this is some sort of bugged out optimization that is supposed to make pages that aren't focused not render, but it's affecting an actually focused page.  ugh.

There were tons and tons and tons of problems like this in WebKit when I used it last.
