### ISSUE TITLE
How to start torch on ios?

### ISSUE THREAD

**Issue by ghevge** [ericblade/quagga2#501]
Hi,
How can I start the torch in ios?

The following code works ok in android, but doesn't do anything in ios:

```
let track = Quagga.CameraAccess.getActiveTrack();
track.applyConstraints({advanced: [{torch: !torchStatus}]});
```

camera permissions are granted, as I can see the camera in ios.

Thanks

**Comment by ericblade** [comment]
I am pretty sure that it is not presently available in iOS.  Sorry :(

**Comment by ericblade** [comment]
Worth mentioning that I've added convenience methods for that to CameraAccess, as enableTorch and disableTorch.  

Are you able to determine if there are any errors generated in the browser in iOS when you try to apply this constraint?  I'd love to know what the result is, so I can determine if there's a way to make it more obvious once it happens.

**Comment by ericblade** [comment]
Documentation for all current CameraAccess functions has been added to README, and noted that torch is not available in known iOS versions.
