### ISSUE TITLE
Cannot find name 'Buffer' on Quagga2 type-definitions

### ISSUE THREAD

**Issue by MasterDataBase** [ericblade/quagga2#509]
Hi all 

I'm start using Quagga, and facing some problem after install Quagga on my Angular project.

And after the tring to import the library `import Quagga from '@ericblade/quagga2';`

I'm facing the following problem: 
`Error: node_modules/@ericblade/quagga2/type-definitions/quagga.d.ts:784:33 - error TS2591: Cannot find name 'Buffer'. Do you need to install type definitions for node? Try `npm i --save-dev @types/node` and then add 'node' to the types field in your tsconfig.`

I tried to install the @types/node and also insert the Type:node in the tsconfig file, but without luck, someone can point me to the right direction?

**Comment by MasterDataBase** [comment]
It seems to work now, the fix in my case was to:

- Install the types/node `npm i --save-dev @types/node`
- Add in the tsconfig.app.json the value `"types": ["node"]` in the `compilerOptions` object

**Comment by yogeshgadge** [comment]
> It seems to work now, the fix in my case was to:
> 
> * Install the types/node `npm i --save-dev @types/node`
> * Add in the tsconfig.app.json the value `"types": ["node"]` in the `compilerOptions` object

Not sure if this is a good workaround to add `"types": ["node"]` to the ` tsconfig.app.json`
If you are targeting browser app we need something better than allowing 'node'

**Comment by ericblade** [comment]
Thanks for bringing this back up.  Decent tools are available now to probably replace the use of Buffer type in here.
https://github.com/ericblade/quagga2/issues/538
