### ISSUE TITLE
how to decode from image from remote url?

### ISSUE THREAD

**Issue by da1z** [ericblade/quagga2#512]
trying to decode from image that i have url for? tried to pass it to decodeSingle and did not work

**Comment by ericblade** [comment]
You'll need to get the image data to the browser or node instance first.  This does not provide a direct way of fetching from the network.

**Comment by ericblade** [comment]
If it helps, here's some ways of getting an image into a form that you can pass through to quagga or any other image manipulation utility

https://pqina.nl/blog/convert-an-image-to-a-base64-string-with-javascript/
