### ISSUE TITLE
Request for new npm release

### ISSUE THREAD

**Issue by DuldR** [ericblade/quagga2#513]
Hello, 

We've noticed that some of the dependency issues were fixed at: https://github.com/ericblade/quagga2/commit/494b496c7ee2919bf47396d447b78c9e3d9342fa

Is it possible to get an updated release to npm for usage downstream?

Thank you for all the hard work on the project!

**Comment by ericblade** [comment]
Thanks for the notice, I've been a bit wrapped up in new dayjob responsibilities. I'll take a look at this first thing tomorrow!

**Comment by ericblade** [comment]
Completed, sorry that took even longer than I suggested :( had to build a javascript environment on the Mac i'm using right now, and I'm not real good with Macs

**Comment by DuldR** [comment]
No worries! Thank you for taking the time out to get it updated, it's very much appreciated.
