### ISSUE TITLE
Quagga.stop not working

### ISSUE THREAD

**Issue by usamahassankhan** [ericblade/quagga2#529]
Hi Eric could you please help why quagga.stop() not stopping the camera  ,it starts fine  but after start we can't stop it ,need your prompt support

**Comment by ericblade** [comment]
When I've encountered this it's always been some code outside of Quagga that is doing something that prevents the browser from detaching the camera.  What is your code doing when you stop?

**Comment by usamahassankhan** [comment]
I think you resolved this issue in quagga 2 ,I am using quagga 1 what do
you  think If I move to quagga 2 ,will it resolved
Plz reply I am fully dependent on your views

**Comment by ericblade** [comment]
I don't know, you could try it, it's a drop-in replacement.  If you show your code, that might help figure out what you're doing

**Comment by ericblade** [comment]
When I personally had this issue, it was calling stop in React unmount, but then the component was being immediately remounted again then unmounted, due to some weird animation interaction.  Difficult to say what yours is doing without seeing code.  The other example you commented on, the stop call is never even being hit, because their code just errors.

**Comment by usamahassankhan** [comment]
Ok, thanks for the reply.

import React, { useEffect } from "react";

import Quagga from "quagga"; it in

import config from "./../../config.json";



const Scanner = (props) => {

  const { onDetected } = props;



  useEffect(() => {

    Quagga.init(config, (err) => {

      if (err) {

        console.log(err, "error msg");

      }

      Quagga.start();

      return () => {

        Quagga.stop();

      };

    });



    //detecting boxes on stream

    Quagga.onProcessed((result) => {

      var drawingCtx = Quagga.canvas.ctx.overlay,

        drawingCanvas = Quagga.canvas.dom.overlay;



      if (result) {

        if (result.boxes) {

          drawingCtx.clearRect(

            0,

            0,

            Number(drawingCanvas.getAttribute("width")),

            Number(drawingCanvas.getAttribute("height"))

          );

          result.boxes

            .filter(function (box) {

              return box !== result.box;

            })

            .forEach(function (box) {

              Quagga.ImageDebug.drawPath(box, { x: 0, y: 1 }, drawingCtx, {

                color: "green",

                lineWidth: 2,

              });

            });

        }



        if (result.box) {

          Quagga.ImageDebug.drawPath(result.box, { x: 0, y: 1 },
drawingCtx, {

            color: "#00F",

            lineWidth: 2,

          });

        }



        if (result.codeResult && result.codeResult.code) {

          Quagga.ImageDebug.drawPath(

            result.line,

            { x: "x", y: "y" },

            drawingCtx,

            { color: "red", lineWidth: 3 }

          );

        }

      }

    });



    Quagga.onDetected(detected);

  }, []);



  const detected = (result) => {

    onDetected(result.codeResult.code);

  };



  return (

    // If you do not specify a target,

    // QuaggaJS would look for an element that matches

    // the CSS selector #interactive.viewport

    <div id="interactive" className="viewport" />

  );

};



export default Scanner;

 This is scanner component




Calling like that

  {IsScannerVIsible && <Scanner onDetected={onDetected} />}

**Comment by ericblade** [comment]
If you re-format your code so it's indented properly

```
import React, { useEffect } from "react";

import Quagga from "quagga";

import config from "./../../config.json";

const Scanner = (props) => {
  const { onDetected } = props;

  useEffect(() => {
    Quagga.init(config, (err) => {
      if (err) {
        console.log(err, "error msg");
      }

      Quagga.start();

      return () => {
        Quagga.stop();
      };
    });

    //detecting boxes on stream

    Quagga.onProcessed((result) => {
      var drawingCtx = Quagga.canvas.ctx.overlay,
        drawingCanvas = Quagga.canvas.dom.overlay;

      if (result) {
        if (result.boxes) {
          drawingCtx.clearRect(
            0,

            0,

            Number(drawingCanvas.getAttribute("width")),

            Number(drawingCanvas.getAttribute("height")),
          );

          result.boxes

            .filter(function (box) {
              return box !== result.box;
            })

            .forEach(function (box) {
              Quagga.ImageDebug.drawPath(box, { x: 0, y: 1 }, drawingCtx, {
                color: "green",

                lineWidth: 2,
              });
            });
        }

        if (result.box) {
          Quagga.ImageDebug.drawPath(result.box, { x: 0, y: 1 }, drawingCtx, {
            color: "#00F",

            lineWidth: 2,
          });
        }

        if (result.codeResult && result.codeResult.code) {
          Quagga.ImageDebug.drawPath(
            result.line,

            { x: "x", y: "y" },

            drawingCtx,

            { color: "red", lineWidth: 3 },
          );
        }
      }
    });

    Quagga.onDetected(detected);
  }, []);

  const detected = (result) => {
    onDetected(result.codeResult.code);
  };

  return (
    // If you do not specify a target,

    // QuaggaJS would look for an element that matches

    // the CSS selector #interactive.viewport

    <div id="interactive" className="viewport" />
  );
};

export default Scanner;
```

You can see on line 18, you are returning the closure that calls Quagga.stop() from Quagga.init() but you need to be returning it from useEffect().  Probably that whole remainder of that block is in the wrong scope, too.

Your Quagga.stop is never being hit.  

You should work to improve your code formatting, so errors like that are more visible when looking at it.  Also, if you used a debugger breakpointed at the stop() call, you would see that it was never being hit .. or just using a console.log() before it.

**Comment by usamahassankhan** [comment]
Thank you so much bro
I made my mistake your code is working fine ,strict mode was on ,It hits
twice  in local that was the reason,
Thank you so much for you reply ,I really appreciate it
