### ISSUE TITLE
Cannot read this bar code with quagga, but can with Java ZXing

### ISSUE THREAD

**Issue by PedroD** [ericblade/quagga2#58]
There are some bar codes that simply do not read well, or at all, here are some examples:

(29749-0004, code 39)
![image](https://user-images.githubusercontent.com/3803097/68083731-3308c000-fe24-11e9-98f1-5d49671dc399.png)

![image](https://user-images.githubusercontent.com/3803097/68083741-50d62500-fe24-11e9-97cf-4c4cf46d957c.png)

**Comment by PedroD** [comment]
Forget it, for some reason errors are not available in code_39 in `barcodeGuess.codeResult.decodedCodes` for average error calculation, so my app was ignoring this because the error was "too high".

**Comment by ericblade** [comment]
Hmm. I only use UPC/EAN, so that's all that I'm particularly familiar with, but that sounds like either a bug or lacking feature in the code_39 reader.

**Comment by PedroD** [comment]
No, it was my mistake. A bug on my own code. I'll close this. Sorry
