### ISSUE TITLE
anyone know what "box" and "boxes" results represent? 

### ISSUE THREAD

**Issue by ericblade** [ericblade/quagga2#77]
... I'm slightly confused as to what the "box" and "boxes" results represent.  'box' appears to be a 4 length array of 2-length arrays, but i'd expect a box would just be a single point pair.. rather than 4 of them.  'boxes' just seems to be an array of that array, though that might be different if multiples are encountered.

**Comment by Denacke** [comment]
If I were to guess without delving in it deeper at the moment, i'd figure those are the 4 x&y-coordinates of the corners of the box? 

Thank you for maintaining this repo by the way!

**Comment by ericblade** [comment]
yeah, i think it might be a good idea to write a sample that visualizes the results in an obvious way (maybe draw some circles/dots at each point in the 'box' / 'boxes' arrays) to get a better idea what is represented there.  

Since you can create a box using just 2 points, one corner, and the opposite corner, it slightly surprised me that it appears to have 4 points, but I guess that makes it easier without having to math out the other points.  I guess I'm used to game engines and UI building engines, where you can easily supply a box with just two points. :-D

So, you're probably right, but I think I might try to add some additional things to the react sample that indicate what the various outputs represent specifically . . . since I'm not the one who designed the output, and it isn't all entirely clear what all the things represent, or their purpose.

**Comment by ChristophKaser** [comment]
I might be wrong, but I don't think 2 points are enough to fully specify a box unless you require it to be axis-aligned. Since quagga supports rotated boxes, this might be the reason for 4 coordinates (just a guess, I did not look at the source)

**Comment by ericblade** [comment]
I hadn't considered that, you are probably right there.  *thinks* have i ever tried to draw a box that wasn't axis aligned to the screen? i am not sure.
